name: build tdlib arm7

on: [push]

jobs:
  armv7_job:
    runs-on: ubuntu-18.04
    name: Build on ARMv7 
    steps:
      - uses: actions/checkout@v1.0.0
      - uses: uraimo/run-on-arch-action@v1.0.5
        id: runcmd
        with:
          architecture: armv7
          distribution: ubuntu18.04
      - name: build
        run: |
            apt install -y g++ ccache openssl cmake gperf make git libssl-dev libreadline-dev zlib1g zlib1g-dev
            openssl version
            uname -a
            cd /
            git clone https://github.com/tdlib/td.git /td
            cd /td
            RUN mkdir build
            cd /build
            cmake -DCMAKE_BUILD_TYPE=Release ..
            make -j 2