name: Build TDLib on Linux ARMv7 

on: [push]

jobs:
  build_job:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@master
        id: runcmd
      - uses: uraimo/run-on-arch-action@master
        name: build
        with:
          architecture: armv7
          distribution: ubuntu18.04
          run: |
            apt update
            apt install -y g++ ccache openssl cmake gperf make git libssl-dev libreadline-dev zlib1g zlib1g-dev
            openssl version
            git clone https://github.com/tdlib/td.git td
            cd td
            mkdir build
            cd build
            cmake -DCMAKE_BUILD_TYPE=Release ..
            make -j 2
            cd td/build/
            ls
      - uses: actions/upload-artifact@master
        name: save artifact
        with:
          name: libtdjson_armv7
          path: td/build/libtdjson.so